[package]
name = "cent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shrinkwraprs = "0.3.0"

[lib]
name = "cent"
path = "src/lib.rs"


[[bin]]
name = "cent"
path = "src/main.rs"
